# $FreeBSD: $

PKGNAMEPREFIX=  powerpc64-
TOOLCHAIN_VARIANT=	-elfv2

X_COMPILER_TYPE=	gcc

PLIST=  ${.CURDIR}/pkg-plist

MASTERDIR=      ${.CURDIR}/../powerpc64-xtoolchain-gcc

.include "${MASTERDIR}/Makefile"

