# $FreeBSD$

COMMENT=	GNU binutils for powerpcspe cross-development
PKGNAMEPREFIX=	powerpcspe-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../binutils

BUTARGET=	e500v2-unknown-${OPSYS:tl}${OSREL}

.include "${MASTERDIR}/Makefile"
